version: 0.2

phases:
  install:
    commands:
      - echo "install"
      - git clone $REPO_URL source
      - mv tests source
      - ls -la
      - curl -fsSL https://bun.sh/install | bash
      - source ~/.bashrc
      - cd source && bun install
  pre_build:
    commands:
      - echo "pre build"
  build:
    commands:
      - echo "build"
      - pwd
      - bun add -D vitest
      - ./node_modules/.bin/vitest
  post_build:
    commands:
      - echo "post_build"
