version: 0.2

phases:
  install:
    commands:
      - echo "install"
      - git clone https://github.com/croffle-dev/10001
      - ls -la
  pre_build:
    commands:
      - echo "pre build"
  build:
    commands:
      - echo "build"
  post_build:
    commands:
      - echo "post_build"
